---
sidebar: sidebar 
permalink: reference_cloud_mgr_reqs.html 
keywords: configurations, ec2, vm, ports, ram, operating system, os, host, requirement, requirements, hypervisor, disk, space, mysql, centos, rhel, red hat, cpu, disk space, 3306 
summary: 자체 호스트에 Cloud Manager를 설치하는 경우 운영 체제 요구사항, 포트 요구사항 등이 포함된 구성에 대한 지원을 확인해야 합니다. 
---
= Cloud Manager 호스트 요구사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
자체 호스트에 Cloud Manager를 설치하는 경우 운영 체제 요구사항, 포트 요구사항 등이 포함된 구성에 대한 지원을 확인해야 합니다.

지원되는 AWS EC2 인스턴스 유형:: T3.MEDIUM(권장), T2.MEDIUM 및 M4.Large
지원되는 Azure VM 크기입니다:: A2, D2 v2 또는 D2 v3(가용성 기준)
지원되는 운영 체제::
+
--
* CentOS 7.2
* CentOS 7.3
* CentOS 7.4
* Red Hat Enterprise Linux 7.2
* Red Hat Enterprise Linux 7.3
* Red Hat Enterprise Linux 7.4
+
Red Hat Enterprise Linux 시스템은 Red Hat 서브스크립션 관리 에 등록되어 있어야 합니다. 등록되지 않은 경우 시스템은 Cloud Manager 설치 중에 필요한 타사 소프트웨어를 업데이트하기 위해 저장소에 액세스할 수 없습니다.

+
Cloud Manager는 이러한 운영 체제의 영어 버전에서 지원됩니다.



--
하이퍼바이저:: CentOS 또는 Red Hat Enterprise Linux 실행 인증을 받은 베어 메탈 또는 호스팅된 하이퍼바이저https://access.redhat.com/certified-hypervisors["Red Hat 솔루션: Red Hat Enterprise Linux 실행 인증을 받은 하이퍼바이저는 무엇입니까?"^]
CPU:: 코어 2개가 있는 경우 2.27GHz 이상
RAM:: 4GB
사용 가능한 디스크 공간:: 50GB
아웃바운드 인터넷 액세스:: Cloud Manager를 설치할 때와 Cloud Manager를 사용하여 Cloud Volumes ONTAP를 구축할 때는 아웃바운드 인터넷 액세스가 필요합니다. 끝점 목록은 을 참조하십시오 link:reference_networking_cloud_manager.html["Cloud Manager의 네트워킹 요구사항"].
포트:: 다음 포트를 사용할 수 있어야 합니다.
+
--
* HTTP 액세스용 80
* HTTPS 액세스용 443
* Cloud Manager 데이터베이스용 3306
* Cloud Manager API 프록시의 경우 8080
+
다른 서비스에서 이러한 포트를 사용하는 경우 Cloud Manager 설치가 실패합니다.

+

NOTE: 포트 3306과 충돌할 가능성이 있습니다. MySQL의 다른 인스턴스가 호스트에서 실행 중인 경우 기본적으로 포트 3306을 사용합니다. 기존 MySQL 인스턴스가 사용하는 포트를 변경해야 합니다.

+
Cloud Manager를 설치할 때 기본 HTTP 및 HTTPS 포트를 변경할 수 있습니다. MySQL 데이터베이스의 기본 포트는 변경할 수 없습니다. HTTP 및 HTTPS 포트를 변경하는 경우 사용자가 원격 호스트에서 Cloud Manager 웹 콘솔에 액세스할 수 있는지 확인해야 합니다.

+
** 포트를 통한 인바운드 연결을 허용하도록 보안 그룹을 수정합니다.
** Cloud Manager 웹 콘솔에 대한 URL을 입력할 때 포트를 지정합니다.




--

