---
sidebar: sidebar 
permalink: reference_limitations.html 
keywords: limitations, active directory, ad, iscsi, key managers, ip address, volume view, govcloud, cloud manager, Cloud Volumes ONTAP 
summary: 알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오. 
---
= 알려진 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오.



== Cloud Manager는 FlexGroup 볼륨을 지원하지 않습니다

Cloud Volumes ONTAP는 FlexGroup 볼륨을 지원하지만 Cloud Manager는 지원하지 않습니다. System Manager 또는 CLI에서 FlexGroup 볼륨을 생성하는 경우 Cloud Manager의 용량 관리 모드를 수동으로 설정해야 합니다. FlexGroup 볼륨에서 자동 모드가 제대로 작동하지 않을 수 있습니다.



== 새로 설치된 Cloud Manager에서는 Active Directory가 기본적으로 지원되지 않습니다

버전 3.4부터 새로 설치된 Cloud Manager는 사용자 관리를 위한 조직의 Active Directory 인증 사용을 지원하지 않습니다. 필요한 경우 NetApp을 통해 Cloud Manager로 Active Directory를 설정할 수 있습니다. Cloud Manager의 오른쪽 아래에 있는 채팅 아이콘을 클릭하여 지원을 받으십시오.



== AWS GovCloud(US) 지역 제한사항

* AWS GovCloud(US) 지역에서 Cloud Volumes ONTAP 인스턴스를 실행하려면 Cloud Manager를 AWS GovCloud(US) 지역에 구축해야 합니다.
* AWS GovCloud(US) 지역에 구축한 경우 Cloud Manager는 Microsoft Azure용 NetApp 프라이빗 스토리지 구성 또는 SoftLayer 구성을 위한 NetApp 프라이빗 스토리지에서 ONTAP 클러스터를 검색할 수 없습니다.




== 볼륨 보기 제한 사항

* 볼륨 뷰는 AWS GovCloud(US) 지역, AWS 상용 클라우드 서비스 환경 및 Microsoft Azure에서 지원되지 않습니다.
* 볼륨 보기를 사용하면 NFS 볼륨만 생성할 수 있습니다.
* Cloud Manager는 볼륨 뷰에서 Cloud Volumes ONTAP BYOL 인스턴스를 시작하지 않습니다.




== Cloud Manager는 iSCSI 볼륨을 설정하지 않습니다

Storage System View를 사용하여 Cloud Manager에서 볼륨을 생성할 때 NFS 또는 CIFS 프로토콜을 선택할 수 있습니다. OnCommand 시스템 관리자를 사용하여 iSCSI용 볼륨을 생성해야 합니다.



== SVM(Storage Virtual Machine) 제한

Cloud Volumes ONTAP는 재해 복구에 사용되는 1개 이상의 SVM과 1개 이상의 SVM을 지원합니다.

Cloud Manager는 SVM 재해 복구에 대한 설정 또는 오케스트레이션 지원을 제공하지 않습니다. 또한 추가 SVM에서 스토리지 관련 작업도 지원하지 않습니다. SVM 재해 복구에 System Manager 또는 CLI를 사용해야 합니다.
