---
sidebar: sidebar 
permalink: reference_default_configs.html 
keywords: linux, user name, operating system, installation files, installation folder, folder, log, logs, service, mysql, packages, linux,  svm, LIF, LIFs, configuration backups, attributes, autosize, security style, space guarantee, unix permissions, NTFS, UNIX, boot, root, disks, aggr0, aggr1, svm, svms, storage virtual machine, LIF failover, failover, attributes, volume attributes, boot disk, root disk 
summary: Cloud Manager 및 Cloud Volumes ONTAP를 기본적으로 구성하는 방법에 대한 자세한 내용은 시스템을 관리하는 데 도움이 됩니다. 
---
= 기본 설정
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Manager 및 Cloud Volumes ONTAP를 기본적으로 구성하는 방법에 대한 자세한 내용은 시스템을 관리하는 데 도움이 됩니다.



== Linux 기반 Cloud Manager의 기본 구성

Cloud Manager 또는 Linux 호스트 문제를 해결해야 하는 경우 Cloud Manager 구성 방법을 이해하는 데 도움이 될 수 있습니다.

* NetApp Cloud Central(또는 AWS Marketplace 또는 Azure Marketplace에서 직접)에서 Cloud Manager를 구축한 경우 다음을 확인하십시오.
+
** AWS에서 EC2 Linux 인스턴스의 사용자 이름은 EC2-user입니다.
** AWS와 Azure 모두에서 Cloud Manager 이미지의 운영 체제는 Red Hat Enterprise Linux 7.4(HVM)입니다.
+
운영 체제에는 GUI가 포함되어 있지 않습니다. 시스템에 액세스하려면 터미널을 사용해야 합니다.



* Cloud Manager 설치 폴더는 다음 위치에 있습니다.
+
/opt/application/netapp/cloudmanager입니다

* 로그 파일은 다음 폴더에 들어 있습니다.
+
/opt/application/netapp/cloudmanager/log입니다

* Cloud Manager 서비스의 이름은 occm입니다.
* occm 서비스는 MySQL 서비스에 따라 달라진다.
+
MySQL 서비스가 다운되면 occm 서비스도 다운됩니다.

* Cloud Manager는 다음 패키지를 아직 설치하지 않은 경우 Linux 호스트에 설치합니다.
+
** 7zip
** AWSCLI
** 자바
** 쿠베틀입니다
** MySQL
** 트리엔ctl
** 윙입니다






== Cloud Volumes ONTAP의 기본 구성입니다

Cloud Volumes ONTAP가 기본적으로 어떻게 구성되어 있는지 이해하면 시스템을 설정하고 관리하는 데 도움이 됩니다. 특히 ONTAP에 익숙한 경우 Cloud Volumes ONTAP의 기본 설정은 ONTAP와 다르기 때문입니다.

* Cloud Volumes ONTAP는 단일 노드 시스템으로, AWS와 Azure 모두에서 HA 쌍으로 사용할 수 있습니다.
* Cloud Volumes ONTAP 구축 시 Cloud Manager에서 단일 데이터 서비스 SVM을 생성합니다. System Manager 또는 CLI에서 다른 데이터 지원 SVM을 생성할 수 있지만, 여러 데이터 제공 SVM을 사용하는 것은 지원되지 않습니다.
* 기본적으로 여러 네트워크 인터페이스가 생성됩니다.
+
** 클러스터 관리 LIF
** 인터클러스터 LIF
** 노드 관리 LIF
** iSCSI 데이터 LIF
** CIFS 및 NFS 데이터 LIF
+

NOTE: EC2 요구사항으로 인해 LIF 페일오버가 Cloud Volumes ONTAP에 대해 기본적으로 비활성화되어 있습니다. LIF를 다른 포트로 마이그레이션하면 IP 주소와 인스턴스 네트워크 인터페이스 간의 외부 매핑이 분리되므로 LIF에 액세스할 수 없습니다.



* Cloud Volumes ONTAP는 HTTPS를 사용하여 구성 백업을 Cloud Manager로 전송합니다.
* Cloud Manager에 로그인하면 에서 백업에 액세스할 수 있습니다 https://ipaddress/occm/offboxconfig/[]
* Cloud Manager에서는 다른 관리 툴(예: System Manager 또는 CLI)과 몇 가지 볼륨 특성을 다르게 설정합니다.
+
다음 표에는 Cloud Manager가 기본값과 다르게 설정하는 볼륨 특성이 나열되어 있습니다.

+
[cols="15,85"]
|===
| 속성 | Cloud Manager에서 설정한 값입니다 


| 자동 크기 조정 모드입니다 | 성장 


| 최대 자동 크기 조정  a| 
1,000%


NOTE: Cloud Manager 관리자는 설정 페이지에서 이 값을 수정할 수 있습니다.



| 보안 스타일 | CIFS 볼륨용 NTFS NFS 볼륨용 UNIX 


| 공간 보장 스타일 | 없음 


| UNIX 권한(NFS에만 해당) | 777 
|===
+
이러한 속성에 대한 자세한 내용은 _volume create_man 페이지를 참조하십시오.





== Cloud Volumes ONTAP의 부팅 및 루트 데이터

사용자 데이터를 위한 스토리지 외에, Cloud Manager는 각 Cloud Volumes ONTAP 시스템에서 부팅 및 루트 데이터를 위한 클라우드 스토리지도 구매합니다.



=== 설치하고

* Cloud Volumes ONTAP 부팅 데이터용 프로비저닝된 IOPS SSD 디스크 1개(약 45GB 및 1,250PIOPS
* Cloud Volumes ONTAP 루트 데이터용 범용 SSD 디스크 1개(약 140GB
* 각 부팅 디스크 및 루트 디스크마다 하나의 EBS 스냅샷


HA 2노드에서 두 Cloud Volumes ONTAP 노드 모두 루트 디스크를 파트너 노드로 복제합니다.



=== Azure를 지원합니다

* Cloud Volumes ONTAP 부팅 데이터용 프리미엄 스토리지 SSD 디스크 1개(약 73GB)
* Cloud Volumes ONTAP 루트 데이터용 프리미엄 스토리지 SSD 디스크 1개(약 140GB)
* 각 부팅 디스크 및 루트 디스크에 대해 Azure 스냅샷 1개




=== 디스크가 상주하는 위치입니다

Cloud Manager는 AWS 및 Azure에서 다음과 같이 스토리지를 구축합니다.

* 부팅 데이터는 EC2 인스턴스 또는 Azure 가상 머신에 연결된 디스크에 있습니다.
+
부팅 이미지가 포함된 이 디스크는 Cloud Volumes ONTAP에서 사용할 수 없습니다.

* 시스템 구성 및 로그가 포함된 루트 데이터는 aggr0에 상주합니다.
* 스토리지 가상 시스템(SVM) 루트 볼륨은 aggr1에 있습니다.
* 데이터 볼륨은 aggr1에도 상주합니다.

