---
sidebar: sidebar 
permalink: task_launching_aws_mktp.html 
keywords: install, installation, installing, marketplace, aws, launch, launching, ec2 console 
summary: NetApp Cloud Central을 사용하여 AWS에서 Cloud Manager를 시작하는 것이 가장 좋으나 필요한 경우 AWS Marketplace에서 시작할 수 있습니다. 
---
= AWS Marketplace에서 Cloud Manager 시작
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AWS에서 Cloud Manager를 시작하는 것이 가장 좋습니다 https://["NetApp Cloud Central에서"^]하지만 필요한 경우 AWS Marketplace에서 시작할 수 있습니다.


TIP: AWS 마켓플레이스에서 Cloud Manager를 시작하면 Cloud Manager가 NetApp Cloud Central과 통합됩니다. link:concept_cloud_central.html["통합에 대해 자세히 알아보십시오"].

.이 작업에 대해
다음 단계에서는 콘솔에서 IAM 역할을 Cloud Manager 인스턴스에 연결할 수 있으므로 EC2 콘솔에서 인스턴스를 시작하는 방법을 설명합니다. 1-클릭 옵션은 사용할 수 없습니다.

.단계
. EC2 인스턴스에 대해 IAM 정책 및 역할을 생성합니다.
+
.. 다음 위치에서 Cloud Manager IAM 정책을 다운로드합니다.
+
https://["NetApp OnCommand 클라우드 관리자: AWS 및 Azure 정책"^]

.. IAM 콘솔에서 Cloud Manager IAM 정책의 텍스트를 복사하여 붙여넣어 고유한 정책을 생성합니다.
.. Amazon EC2 역할 유형으로 IAM 역할을 생성하고 이전 단계에서 생성한 정책을 역할에 연결합니다.


. 로 이동합니다 https://["Cloud Manager 페이지로 이동하여 AWS 마켓플레이스를 확인하십시오"^].
. 계속 * 을 클릭합니다.
. 사용자 지정 시작 탭에서 해당 지역의 * EC2 콘솔 * 로 시작 을 클릭한 후 다음을 선택합니다.
+
.. 지역 사용 가능 여부에 따라 T3.MEDIUM(권장), T2.MEDIUM 또는 M4.Large instance type을 선택합니다.
.. 요구 사항을 충족하는 VPC, 서브넷, IAM 역할 및 기타 구성 옵션을 선택합니다.
.. 기본 스토리지 옵션을 유지합니다.
.. 필요한 경우 인스턴스에 대한 태그를 입력합니다.
.. Cloud Manager 인스턴스에 필요한 SSH, HTTP 및 HTTPS 연결 방법을 지정합니다.
.. 시작 * 을 클릭합니다.




.결과
AWS가 지정된 설정으로 소프트웨어를 시작합니다. Cloud Manager 인스턴스와 소프트웨어는 약 5분 내에 실행되어야 합니다.

.작업을 마친 후
웹 브라우저에 공용 IP 주소 또는 전용 IP 주소를 입력하여 Cloud Manager에 로그인한 다음 설정 마법사를 완료합니다.
